config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :update, :edit, :show, :index]
  resources :matches, only: [:create, :show, :index]

  resources :matches do
    resources :messages, only: :create
  end
  
  post "users/:id/like", to: "users#like", as: "like_user"
  root 'users#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  has_many :messages
  has_many :users_matches
  has_many :users, through: :users_matches
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :match
  belongs_to :user
  validates :content, presence: true,length: { minimum: 1 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :users_matches
  has_many :messages
  has_many :matches, through: :users_matches

  validates :email, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true, length: { minimum: 2 }
  validates :surname, presence: true, length: { minimum: 2 }

  def like(liked_user)
    update(likes: likes + [liked_user.id])

    return unless liked_user.likes.include?(id)

    Match.create(users: [self, liked_user])
  end
end

app/models/users_match.rb
# frozen_string_literal: true

class UsersMatch < ApplicationRecord
  belongs_to :user
  belongs_to :match
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :founderror

  private

  def founderror(exception)
    logger.warn exception
    render file: 'public/404.html', status: :not_found, layout: false
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def signed_in?
    current_user.present?
  end

  def no_signed_in?
    !current_user.present?
  end

  def sign_out
    session.delete :user_id
  end

  def no_authentication
    return if no_signed_in?

    redirect_to root_path
  end

  def authentication
    return if signed_in?

    redirect_to root_path
  end

  helper_method :current_user, :signed_in?
  helper_method :current_user, :no_signed_in?
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  before_action :receive_before, only: :show
  before_action :no_authentication, only: %i[new create]
  before_action :authentication, only: %i[index show]

  def create; end

  def show
    @messages = @match.messages.includes(:user)
    @message = Message.new
  end

  def index
    @matches = current_user.matches.includes(:users)
  end

  def receive_before
    @match = Match.find params[:id]
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :receive_match

  def create
    message = @match.messages.build recieve_params_for_new

    redirect_to match_path(@match) if message.save
  end

  def recieve_params_for_new
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end

  def receive_match
    @match = Match.find params[:match_id]
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :no_authentication, only: %i[new create]
  def new; end

  def create
    user = User.find_by email: params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in.\nWelcome to the gym, #{user.name}!"
      redirect_to root_path
    else
      flash[:warning] = 'Data entered incorrectly'
      redirect_to new_session_path
    end
  end

  def destroy
    sign_out
    flash[:success] = "You have successfully logged out.\nGet back to the gym soon!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :no_authentication, only: %i[new create]
  before_action :authentication, only: %i[show edit update like]
  before_action :receive_before, only: %i[edit update show]
  before_action :authorization, only: %i[update edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new receive_params_for_new
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_user_path
      flash[:danger] = 'An error has occurred, perhaps a user with such an email is already registered'
    end
  end

  def update
    if @user.update receive_params_for_update
      redirect_to root_path
      flash[:success] = 'You have successfully edited profile.'
    else
      render :edit
    end
  end

  def edit; end

  def show; end

  def index
    @users = User.all.reject { |user| current_user&.likes&.include?(user.id) }
  end

  def like
    current_user.like(User.find receive_liked_user_id)
    redirect_to users_path
  end

  def receive_before
    @user = User.find params[:id]
  end

  def receive_params_for_new
    params.require(:user).permit(:email, :name, :surname, :password, :password_confirmation)
  end

  def receive_params_for_update
    params.require(:user).permit(:email, :name, :surname, :information)
  end

  def receive_liked_user_id
    params[:id].to_i
  end

  def authorization
    return if current_user == @user

    flash[:warning] = 'you can\'t edit other users'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

module MainHelper
end

app/helpers/mathes_helper.rb
# frozen_string_literal: true

module MathesHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
    %head
        %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
        %meta{charset: "utf-8"}/
        %title WriteNow
        %meta{content: "width=device-width,initial-scale=1", name: "viewport"}/
        = csrf_meta_tags
        = csp_meta_tag
        = stylesheet_link_tag "application", "data-turbo-track": "reload"
        = javascript_importmap_tags
    %body
        %header.p-3.bg-dark.text-white
            .container
                .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
                    %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{href: "/"}
                        %svg.bi.me-2{"aria-label" => "Bootstrap", height: "32", role: "img", width: "40"}
                        %use{"xlink:href" => "#bootstrap"}
                    %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
                        %li= link_to 'Home', root_path, class: "nav-link px-2 text-white"
                        %li
                        = link_to 'Matches', matches_path, class: "nav-link px-2 text-white"
                    - if signed_in?
                        .text-end
                        = link_to "#{current_user.name}", edit_user_path(current_user), class: "btn btn-dark text-warning me-2"
                        = link_to 'log out', session_path, class: "btn btn-outline-danger me-2",        |
                            data: {turbo_method: :delete, confirm: 'Are you sure you want to log out?'} |
                    - else
                        .text-end
                        = link_to 'Log in', new_session_path, class: "btn btn-outline-light me-2"
                        = link_to 'Sign up', new_user_path, class: "btn btn-warning"
    
        %main.container.mt-3
            - flash.each do |k, v|
                = tag.div v, class: "alert alert-#{k}", role: "alert"
            = yield

app/views/matches/index.html.haml
%h1 Matches
- @matches.each do |match|
    %span{:hidden => "until-found"}
        = user = match.users.detect { |user| user != current_user}
    .my-3.p-3.bg-body.rounded.shadow-sm
        %h1
            = link_to "#{user.name} #{user.surname}", match_path(match), class: "btn btn-light text-dark me-2"
        .d-flex.text-muted.pt-3
            %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
                %title Placeholder
                %rect{:fill => "#007bff", :height => "100%", :width => "100%"}
                %text{:dy => ".3em", :fill => "#007bff", :x => "50%", :y => "50%"} 32x32


            .pb-3.mb-0.small.lh-sm.border-bottom.w-100
                .d-flex.justify-content-between
                    %span.d-block= "@#{user.name} #{user.surname}"
                    %hr
                %pre= user.information

app/views/matches/show.html.haml
%h1 Match
%hr
.my-3.p-3.bg-body.rounded.shadow-sm
    - @messages.each do |message|
        - if message.user == current_user
            .d-flex.text-muted.pt-3
                %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
                    %title Placeholder
                    %rect{:fill => "#007bff", :height => "100%", :width => "100%"}
                    %text{:dy => ".3em", :fill => "#007bff", :x => "50%", :y => "50%"} 32x32
                %p.pb-3.mb-0.small.lh-sm.border-bottom
                    %strong.d-block.text-gray-dark
                        = "@#{message.user.name}"
                    = "#{message.content}"
        - else
            .d-flex.text-muted.pt-3
                %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", :focusable => "false", :height => "32", :preserveaspectratio => "xMidYMid slice", :role => "img", :width => "32", :xmlns => "http://www.w3.org/2000/svg"}
                    %title Placeholder
                    %rect{:fill => "#e83e8c", :height => "100%", :width => "100%"}
                    %text{:dy => ".3em", :fill => "#e83e8c", :x => "50%", :y => "50%"} 32x32
                %p.pb-3.mb-0.small.lh-sm.border-bottom
                    %strong.d-block.text-gray-dark
                        = "@#{message.user.name}"
                    = "#{message.content}"

= form_with model: [@match, @message], class: "card p-2", remote: true do |form|
    .input-group
        .col-sm-10
            = form.text_area :content, required: true, minlength: 1, placeholder: "What are you doing?", class: "form-control"
    .mt-3
        = form.submit "Submit", class: "btn btn-success"

app/views/users/edit.html.haml
%h1.mb-4 Edit Profile
%hr
.article
    .card-body.bg-light.text-dark.col-lg-5.col-md-5.col-sm-5px-md-4
        = form_with model: @user, class:"p-2" do |f| 
        
            .mb-3.row
                = f.label "Email", class: "col-sm-2 col-form-label" 
                %br
                    .col-sm-10
                        = f.email_field :email, required: true, minlength: 6, value:"#{current_user.email}",  placeholder: "example@email.com", class: "form-control"

            .mb-3.row
                = f.label "Name", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.text_field :name, required: true, minlength: 2, value:"#{current_user.name}", placeholder: "Jpyatachkov", class: "form-control"

            .mb-3.row
                = f.label "Surname", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.text_field :surname, required: true, minlength: 2, value: "#{current_user.surname}", placeholder: "", class: "form-control"

            .mb-3.row
                = f.label "Information", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.text_area :information, required: true, minlength: 2, value: "#{current_user.information}", placeholder: "", class: "form-control"

            -# .mb-3.row
            -#     = f.label "Password", class: "col-sm-2 col-form-label"
            -#     %br
            -#     .col-sm-10
            -#         = f.password_field :password, required: true, minlength: 4,  class: "form-control"


            -# .mb-3.row
            -#     = f.label "Confirmation password", class: "col-sm-2 col-form-label"
            -#     %br
            -#     .col-sm-10
            -#         = f.password_field :password_confirmation, required: true, minlength: 4, class: "form-control"
            = f.submit "Submit", class: "btn btn-success mb-2"

app/views/users/index.html.haml
- if signed_in? 
    %h1 Users
    - @users.each do |user|
        - unless user.id == current_user.id
            .my-3.p-3.bg-body.rounded.shadow-sm
                .d-flex.text-muted.pt-3
                    %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", focusable: "false", height: "32", preserveaspectratio: "xMidYMid slice", role: "img", width: "32", xmlns: "http://www.w3.org/2000/svg"}
                        %title Placeholder
                        %rect{fill: "#007bff", height: "100%", width: "100%"}
                        %text{dy: ".3em", fill: "#007bff", x: "50%", y: "50%"} 32x32

                    .pb-3.mb-0.small.lh-sm.border-bottom.w-100
                        .d-flex.justify-content-between
                            %strong.text-gray-dar
                                = link_to "@#{user.name} #{user.surname}", user_path(user.id), class: "nav-link px-2 text-dark"
                            = button_to "Like" , like_user_path(user.id), class: "btn btn-danger"


- else
    %p>
        = link_to "Not registered yet? Then click", new_user_path, class: "nav-link px-2 text-primary"

app/views/users/new.html.haml
%h1.mb-4 Registration
%hr
.article
    .card-body.bg-light.text-dark.col-lg-5.col-md-5.col-sm-5px-md-4
        = form_with model: @user, class:"p-2" do |f| 
        
            .mb-3.row
                = f.label "Email", class: "col-sm-2 col-form-label" 
                %br
                    .col-sm-10
                        = f.email_field :email, required: true, minlength: 6, placeholder: "example@email.com", class: "form-control"

            .mb-3.row
                = f.label "Name", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.text_field :name, required: true, minlength: 2, placeholder: "Jpyatachkov", class: "form-control"

            .mb-3.row
                = f.label "Surname", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.text_field :surname, required: true, minlength: 2, placeholder: "", class: "form-control"

            .mb-3.row
                = f.label "Password", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.password_field :password, required: true, minlength: 4,  class: "form-control"


            .mb-3.row
                = f.label "Confirmation password", class: "col-sm-2 col-form-label"
                %br
                .col-sm-10
                    = f.password_field :password_confirmation, required: true, minlength: 4, class: "form-control"
            = f.submit "Submit", class: "btn btn-success mb-2"

app/views/users/show.html.haml
%h1= "#{@user.name} #{@user.surname}"
%hr
.my-3.p-3.bg-body.rounded.shadow-sm
    .d-flex.text-muted.pt-3
        %svg.bd-placeholder-img.flex-shrink-0.me-2.rounded{"aria-label" => "Placeholder: 32x32", focusable: "false", height: "32", preserveaspectratio: "xMidYMid slice", role: "img", width: "32", xmlns: "http://www.w3.org/2000/svg"}
            %title Placeholder
            %rect{fill: "#007bff", height: "100%", width: "100%"}
            %text{dy: ".3em", fill: "#007bff", x: "50%", y: "50%"} 32x32
        .pb-3.mb-0.small.lh-sm.border-bottom.w-100
            .d-flex.justify-content-between
                .d-block= "@#{@user.name} #{@user.surname}"
                %hr
                = button_to "Like" , like_user_path(@user.id), class: "btn btn-danger"
            %pre= @user.information